### ISSUE TITLE
Date and Time

### ISSUE THREAD

**Issue by seansgm** [tburgin/AbsoluteManageExport#1]
Is it possible to set the Date and Time during the process beyond editing the ampkgprops file?  Eg. Current Time or perhaps Current Time plus amount of time in days, hours, etc.

**Comment by tburgin** [comment]
If `sdpackages_ampkgprops_path` is not defined in the recipe, a default ampkgprops will be generated. Apart of that is setting the `AvailabilityDate` using `datetime.datetime.today()`. It is on line 74, I do need to break up that line a bit, it is too long.

  *  https://github.com/tburgin/AbsoluteManageExport/blob/master/AbsoluteManageExport.py#L74

We could add an optional recipe input that would be something like `add_s_to_availability_date`. I am curious about your setup. Without defining an ampkgprops the package will not be assigned to any deployment groups. What good does settings the AvailabilityDate do?

**Comment by seansgm** [comment]
That is indeed a very long line! 

I've had issues with default ampkgprops generation and timings, since it is an hour out (it's a BST thing).  So being able to set the time or having the correct time pulled through would be good .  An additional thought was that by setting the time into the future, it will prevent anyone in the team pushing it until it is checked by an Admin that has permissions to change this.

**Comment by tburgin** [comment]
I implemented `add_s_to_availability_date` to take an `integer` as a recipe option. It works well for me. Give it a shot. Everything is in seconds. So one day is `86400` seconds.

**Comment by seansgm** [comment]
Wow, thanks for the fast turn around!  I've re-run the same recipe changing the values and it looks good.  I've added and subtracted time, subtracting 3600 giving me current time BST and it's ignoring the AvailabilityDate in the ampkgprops file.
I'm sure others will find this a useful addition and glad you felt is was worth doing.

**Comment by tburgin** [comment]
I'm glad it works for you. Added bonus, I didn't even think about negative integers. Glad Python handles them and datetime does the math!

**Comment by seansgm** [comment]
Can you add process arguments to a recipe override?  So for Firefox you could for example change the LOCALE, but what if I wanted to add the add_s_to_availability_date to an override? So far I just copied your recipes and edited them to allow for the add_s_to_availability_date, but ideally this would be in an override recipe.

**Comment by seansgm** [comment]
Just answered my own question.  First attempts didn't work, but I've just changed it and it now appears to have worked.
