### ISSUE TITLE
All new uploads are tageted to the Windows Platform

### ISSUE THREAD

**Issue by BadStreff** [tburgin/AbsoluteManageExport#18]
Just as the title says, I believe the offending code is in lines 379-380 of the AbsoluteManageExport.py file.

I cannot for the life of me get the formatting correct but these are the lines.
`if platform_arch is not None: os_platform = 4`

I am submitting a pull request of what I believe the be the desired check.

**Comment by BadStreff** [comment]
Here is the pull request: https://github.com/tburgin/AbsoluteManageExport/pull/19

**Comment by jbaker10** [comment]
Please try the newest version/commit to make sure the issue is resolved for you.

See my reply to your pull request https://github.com/tburgin/AbsoluteManageExport/pull/19 for more info.

**Comment by BadStreff** [comment]
No longer having this issue, thanks!

**Comment by jbaker10** [comment]
:+1:
