### ISSUE TITLE
Released pkg was not versioned

### ISSUE THREAD

**Issue by patgmac** [tburgin/AbsoluteManageExport#20]
0.4.1 release package still has 0.4.0 in the pkginfo which causes AutoPkgr to freak out. 

`$ pkgutil --pkg-info com.github.tburgin.AbsoluteManageExport
package-id: com.github.tburgin.AbsoluteManageExport
version: 0.4.0
volume: /
location: 
install-time: 1455125627`

**Comment by jbaker10** [comment]
Thanks, merged your request: https://github.com/tburgin/AbsoluteManageExport/pull/21
