### ISSUE TITLE
DatabaseDirectory location

### ISSUE THREAD

**Issue by patgmac** [tburgin/AbsoluteManageExport#3]
The instructions state there should be a database at ~/Library/Application Support/LANrev Admin/Database/. But what if someone redirects their DB to a different location using the DatabaseDirectory key in com.poleposition-sw.lanrev_admin.plist? Could you look to that value instead of assuming the db is in the default location?

**Comment by tburgin** [comment]
Cool, didn't know you can redirect the database location. We can check to see if the key exists. If so, use that path, if not revert to the default.

Do you have a pull request, or should I implement this?

**Comment by patgmac** [comment]
Given my lack of Python experience....

**Comment by tburgin** [comment]
No worries. I will put it on my todo list.

**Comment by tburgin** [comment]
Have not had the time. I should get to it this week.

**Comment by patgmac** [comment]
No problem. Thanks!

**Comment by seansgm** [comment]
Can you symlink it for the moment?

**Comment by patgmac** [comment]
No, I have my LANrev Admin folder symlinked to my Dropbox so I can have the
same settings on all my computers which is why I change the location of my
db. . Symlinking my DB folder would mean my DB's would be synced in
Dropbox.

**Comment by tburgin** [comment]
@patgmac Can you show me your `DatabaseDirectory` value? Trying to build out the path, just don't know if `DatabaseDirectory` included the server name or if I need to add it.

**Comment by patgmac** [comment]
Does not include server name. Just file system directory. Such as
~/LANrevDB or /Volumes/drive/lanrevdb

**Comment by tburgin** [comment]
Latest Push should do the trick. Let me know.
https://github.com/tburgin/AbsoluteManageExport/commit/e7d1951d1e214cb180d2975416da3b784f0b5fe9

**Comment by tburgin** [comment]
@patgmac Work out? Okay to close?

**Comment by patgmac** [comment]
Sorry for the delay. Yes, it is working now. Thanks!
