### ISSUE TITLE
Skype failing to upload after new download

### ISSUE THREAD

**Issue by seansgm** [tburgin/AbsoluteManageExport#4]
On 28th May Skype 7.8 was downloaded and pushed to our Absolute server.
On 30th May and today (03 June), the dmg was downloaded again, but same version, so neither of these times was it uploaded to Absolute.

Reading the created plist file 'new_downloads'

(
"/Volumes/DATA/autopkg/Cache/io.github.hjuutilainen.pkg.ExifTool/downloads/ExifTool.dmg",
"/Volumes/DATA/autopkg/Cache/local.Future.Absolute.Dropbox/downloads/Dropbox.dmg",
"/Volumes/DATA/autopkg/Cache/local.Future.Absolute.Firefox/downloads/Firefox.dmg",
"/Volumes/DATA/autopkg/Cache/local.Future.Absolute.Skype/downloads/Skype.dmg"
)

Processing Skype.Absolute.Future.recipe...
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 02 Jun 2015 17:46:06 GMT
URLDownloader: Storing new ETag header: "556debde-25414c9"
URLDownloader: Downloaded

AbsoluteManageExport: [+] [Skype-7.8.pkg] already exists in Absolute Manage Server Center
AbsoluteManageExport: [+] Nothing uploaded to Absolute Manage

I've had confirmation from timsutton that all is well on the downloader; https://github.com/autopkg/recipes/issues/88

Looking at the newly downloaded file from today, compared with at the end of May shows that it is a newer version, but as version number reported back is the CFBundleVersion it appears the same even though it is newer.

May 30th:

defaults read /Applications/Skype.app/Contents/Info CFBundleShortVersionString CFBundleVersion
7.8
defaults read /Applications/Skype.app/Contents/Info CFBundleVersion
7.8.0.388

June 3rd:

read /Volumes/Skype/Skype.app/Contents/Info CFBundleShortVersionString
7.8
defaults read /Volumes/Skype/Skype.app/Contents/Info CFBundleVersion
7.8.0.391

**Comment by tburgin** [comment]
@seansgm @timsutton

AbsoluteManageExport does checks based on the Payload's `ExecutableName`. It seems in both cases the payload name is `Skype-7.8.pkg`.

```
AbsoluteManageExport: [+] [Skype-7.8.pkg] already exists in Absolute Manage Server Center
AbsoluteManageExport: [+] Nothing uploaded to Absolute Manage
```

Two ways to fix this:

1. Go into your Absolute Manage server and delete the package and payload for Skype 7.8. Then re-run the recipe. AbsoluteManageExport should not detect any payloads with an executable name of `Skype-7.8.pkg` and upload the package.

2. Modify the Skype --> PKG recipe to give the package a more verbose version number.

**Comment by timsutton** [comment]
Sorry, I didn't realize this was dependent on the version in the pkg recipe in autopkg/recipes. I'll update it shortly.

**Comment by timsutton** [comment]
Should be fixed here: https://github.com/autopkg/recipes/commit/4e5da6e6e0c788ba15b748cd5c1028f10dad456f

**Comment by tburgin** [comment]
Thanks @timsutton
