### ISSUE TITLE
Incorrect version in Pkg installer receipt.

### ISSUE THREAD

**Issue by eahrold** [tburgin/AbsoluteManageExport#5]
Hey Tom, 
I wanted to let you know that the `PackageVersion` of the 0.3 installer is showing as 1.0 in the `/private/var/db/receipts/com.github.tburgin.AbsoluteManageExport.plist`.

**Comment by tburgin** [comment]
Thanks. Updated the Package Version.
https://github.com/tburgin/AbsoluteManageExport/commit/a30fd2c7fefb143816ee0712515b561c3bdb85af

**Comment by eahrold** [comment]
:+1: 

I also wanted to ask, are you OK with us integrating this into AutoPkgr?

![abminstalled](https://cloud.githubusercontent.com/assets/3740088/8010417/aa76a2a2-0b75-11e5-822a-a720b97c6aaa.png)

**Comment by tburgin** [comment]
GoGoGo! Looks great!
