### ISSUE TITLE
At a loss on setup

### ISSUE THREAD

**Issue by jfuchtm** [tburgin/AbsoluteManageExport#7]
I have installed the latest version of AutoPkgR with AMExporter.  I am at a loss on setup. I have AM Admin on the same machine but I am not grasping on export or function.  Any help would be appreciated.

Thanks
-Jeff

**Comment by tburgin** [comment]
Hey @jfuchtm, you will need a recipe that makes use of the AMExporter processor. Can you post a recipe you are tying to run?

**Comment by jfuchtm** [comment]
Just the standard recipes that are part of AutoPkgR already.  Just edit the
recipe already in place?

Thanks

Jeff Uchtman 
District Network & Systems Administrator
Columbus Public Schools
2508 27th Street
Columbus, NE 68601
402-563-7000 ext.1504

uchtmanj@discoverers.org <mailto:uchtmanj@discoverers.org>


In God we trust, all others we virus scan.  ~Author Unknown



From:  Tom Burgin <notifications@github.com>
Reply-To:  tburgin/AbsoluteManageExport
<reply+0080c847f40f0f6bdb3081b4e88df1e2bd8dc684dfe4553492cf0000000111cf547a9
2a169ce05d3165e@reply.github.com>
Date:  Tuesday, July 28, 2015 at 9:32 AM
To:  tburgin/AbsoluteManageExport <AbsoluteManageExport@noreply.github.com>
Cc:  Jeffrey Uchtman <uchtmanj@discoverers.org>
Subject:  Re: [AbsoluteManageExport] At a loss on setup (#7)


Hey @jfuchtm <https://github.com/jfuchtm> , you will need a recipe that
makes use of the AMExporter processor. Can you post a recipe you are tying
to run?


Reply to this email directly or view it on GitHub
<https://github.com/tburgin/AbsoluteManageExport/issues/7#issuecomment-12562
8233> .

**Comment by tburgin** [comment]
Take a look here https://github.com/autopkg/seansgm-recipes
@seansgm has posted many Absolute recipes

**Comment by jfuchtm** [comment]
Thanks, I found the missing link.


Jeff Uchtman 
District Network & Systems Administrator
Columbus Public Schools
2508 27th Street
Columbus, NE 68601
402-563-7000 ext.1504

uchtmanj@discoverers.org <mailto:uchtmanj@discoverers.org>


In God we trust, all others we virus scan.  ~Author Unknown



From:  Tom Burgin <notifications@github.com>
Reply-To:  tburgin/AbsoluteManageExport
<reply+0080c8475a7c91978552dff03ca864f2847b6b65d1c732ed92cf0000000111cf56d49
2a169ce05d3165e@reply.github.com>
Date:  Tuesday, July 28, 2015 at 9:42 AM
To:  tburgin/AbsoluteManageExport <AbsoluteManageExport@noreply.github.com>
Cc:  Jeffrey Uchtman <uchtmanj@discoverers.org>
Subject:  Re: [AbsoluteManageExport] At a loss on setup (#7)


Take a look here https://github.com/autopkg/seansgm-recipes
@seansgm <https://github.com/seansgm>  has posted many Absolute recipes


Reply to this email directly or view it on GitHub
<https://github.com/tburgin/AbsoluteManageExport/issues/7#issuecomment-12563
3005> .

**Comment by tburgin** [comment]
Awesome, enjoy!
