### ISSUE TITLE
Problem running multiple recipes from Autopkgr

### ISSUE THREAD

**Issue by patgmac** [tburgin/AbsoluteManageExport#8]
When running a series of recipes from  (or probably multiple recipes from outside of Autopkgr as well), the AM console displays errors if the previous recipe was not finished uploading. 

<img width="940" alt="screen shot 2015-08-19 at 8 15 28 pm" src="https://cloud.githubusercontent.com/assets/614564/9372709/bee44698-46af-11e5-9690-40d5d2d190af.png">

The result is that the console usually freezes up and 1 or more of the packages are not properly added/uploaded to AM. After eventually dismissing the errors and saving changes to the server, sometimes the payloads are not properly uploaded (indicated by the "upload status" information item). 

Aug 19 19:51:28 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 19:52:31 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Received 'Check Now' menulet command.
Aug 19 19:52:33 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 19:52:33 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.seansgm-recipes...
Aug 19 19:52:34 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.patgmac-recipes...
Aug 19 19:52:35 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes...
Aug 19 19:52:36 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes...
Aug 19 19:52:36 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
Aug 19 19:52:37 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes...
Aug 19 19:52:37 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes...
Aug 19 19:52:38 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes...
Aug 19 19:52:38 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.Evernote...
Aug 19 19:52:39 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 19:56:43 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: Evernote_RELEASE_6.0.16_451861:6.0.16
Aug 19 19:58:10 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.CrystalMaker...
Aug 19 19:58:25 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 20:00:39 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: CrystalMaker:9.2.3
Aug 19 20:00:55 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.CrystalDiffract...
Aug 19 20:01:12 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 20:01:58 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: CrystalDiffract:6.5.3
Aug 19 20:02:08 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.AdobeReaderDC...
Aug 19 20:03:35 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 20:05:25 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 20:05:57 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: AdobeReaderDC:15.008.20082
Aug 19 20:06:05 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.AdobeAcrobatProXIUpdate...
Aug 19 20:06:26 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 20:06:30 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Canceling /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/pgalla2/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/y2/zc31smvd50j8jtwqg14lj8kjrbxhc7/T/com.lindegroup.AutoPkgr/20150819195232 -v
Aug 19 20:06:30 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/pgalla2/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/y2/zc31smvd50j8jtwqg14lj8kjrbxhc7/T/com.lindegroup.AutoPkgr/20150819195232 -v
Aug 19 20:06:30 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-update all
Aug 19 20:07:23 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Received 'Check Now' menulet command.
Aug 19 20:07:24 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 20:07:24 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.seansgm-recipes...
Aug 19 20:07:26 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.patgmac-recipes...
Aug 19 20:07:26 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes...
Aug 19 20:07:27 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes...
Aug 19 20:07:27 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
Aug 19 20:07:28 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes...
Aug 19 20:07:29 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes...
Aug 19 20:07:29 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes...
Aug 19 20:07:30 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.SingleCrystal...
Aug 19 20:07:30 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 20:09:22 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: SingleCrystal:2.3.3
Aug 19 20:09:31 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.CrystalMaker...
Aug 19 20:09:33 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: CrystalMaker:9.2.3
Aug 19 20:09:42 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.CrystalDiffract...
Aug 19 20:09:44 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: CrystalDiffract:6.5.3
Aug 19 20:09:50 col-pgalla2-03i AutoPkgr[68839]: Error [1] Error running recipes 
Aug 19 20:09:50 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/pgalla2/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/y2/zc31smvd50j8jtwqg14lj8kjrbxhc7/T/com.lindegroup.AutoPkgr/20150819200723 -v
Aug 19 20:09:50 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-update all
Aug 19 20:10:39 col-pgalla2-03i AutoPkgr[68839]: Missing Parent Recipe
Aug 19 20:11:02 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Received 'Check Now' menulet command.
Aug 19 20:11:04 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 20:11:04 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.seansgm-recipes...
Aug 19 20:11:07 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.patgmac-recipes...
Aug 19 20:11:09 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes...
Aug 19 20:11:11 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes...
Aug 19 20:11:13 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
Aug 19 20:11:15 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes...
Aug 19 20:11:18 col-pgalla2-03i AutoPkgr[68839]: Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes...
Aug 19 20:11:20 col-pgalla2-03i AutoPkgr[68839]: Already up-to-date.
	Attempting git pull for /Users/pgalla2/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes...
Aug 19 20:11:22 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.Evernote...
Aug 19 20:11:22 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 20:11:30 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: Evernote_RELEASE_6.0.16_451861:6.0.16
Aug 19 20:12:32 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.SingleCrystal...
Aug 19 20:12:34 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: SingleCrystal:2.3.3
Aug 19 20:12:46 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.CrystalMaker...
Aug 19 20:12:48 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: CrystalMaker:9.2.3
Aug 19 20:13:29 col-pgalla2-03i AutoPkgr[68839]: Processing com.github.patgmac.absolute.CrystalDiffract...
Aug 19 20:13:32 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Found app and version: CrystalDiffract:6.5.3
Aug 19 20:14:09 col-pgalla2-03i AutoPkgr[68839]: Error [1] Error running recipes 
Aug 19 20:14:09 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/pgalla2/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/y2/zc31smvd50j8jtwqg14lj8kjrbxhc7/T/com.lindegroup.AutoPkgr/20150819201103 -v
Aug 19 20:14:09 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-update all
Aug 19 20:26:16 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Activated AutoPkgr configuration window.
Aug 19 20:26:29 col-pgalla2-03i AutoPkgr[68839]: Adding https://github.com/autopkg/arubdesu-recipes.git
Aug 19 20:26:29 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list
Aug 19 20:26:35 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-add https://github.com/autopkg/arubdesu-recipes.git
Aug 19 20:26:35 col-pgalla2-03i AutoPkgr[68839]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg repo-list

**Comment by tburgin** [comment]
A few ideas:

1. Detect the number of recipes in the list. Then only commit to upload during the last recipe.
2. Detect the upload state of the `LANrev Admin.app`. Wait for each upload to finish before continuing.

I prefer number two. This will mitigate upload failures by only uploading one payload at a time.

Suggestions are welcome.

**Comment by tburgin** [comment]
Not the most elegant, but it works for me.
Let me know if this fixes your issues.

**Comment by patgmac** [comment]
Working well so far. Thanks for taking care of this so fast!

**Comment by tburgin** [comment]
👍

**Comment by patgmac** [comment]
I did hear back from Martin who said he will try to get something like --GetSDStateString into the next version. Anyone interested should request their name be added to COBRA-22160.

**Comment by seansgm** [comment]
I have seen machines that report they cannot contact the server when using
--GetSDStateString , even though they appear to be working correctly, so I
don't know how consistent this could be.  I recall being warned of the
options not necessarily working as expected by support.
